services:
  app:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: ./builder/local/Dockerfile
    container_name: app-ujol
    volumes:
      - .:/var/www/html
    networks:
      - app-bridge

  app-prod:
    profiles: ["prod"]
    build:
      context: .
      dockerfile: ./builder/prod/Dockerfile
    container_name: app-ujol-prod
    restart: always
    volumes:
      - .:/var/www/html
    networks:
      - app-bridge

  webserver:
    image: nginx:stable-alpine
    container_name: nginx-ujol
    profiles: ["dev"]
    ports:
      - "8080:8080"
      - "5173:5173"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf   # Menyambungkan file konfigurasi Nginx
      - .:/var/www/html   # Menyambungkan folder app ke dalam container
    depends_on:
      - app
    networks:
      - app-bridge

  webserver-prod:
    image: nginx:stable-alpine
    container_name: nginx-ujol-prod
    restart: always
    profiles: ["prod"]
    ports:
      - "3000:80" # 82 untuk nginx 01 untuk pengenal container
    volumes:
      - ./nginx-prod.conf:/etc/nginx/conf.d/default.conf   # Menyambungkan file konfigurasi Nginx
      - .:/var/www/html   # Menyambungkan folder app ke dalam container
    depends_on:
      - app-prod
    networks:
      - app-bridge

  redis:
    image: redis:latest
    container_name: redis-ujol
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ./redis:/data
    networks:
      - app-bridge

  mailpit:
    image: axllent/mailpit
    container_name: mailpit-ujol
    profiles: ["dev"]
    ports:
      - "8025:8025"     # Web UI
      - "1025:1025"     # SMTP
    networks:
      - app-bridge

  adminer:
    image: adminer
    container_name: adminer-ujol
    restart: always
    ports:
      - 8801:8080 # 88 untuk adminer 01 untuk pengenal container
    networks:
      - app-bridge

networks:
  app-bridge:
    external: true